- name: Allow node-exporter over local IPv4
  ufw:
    rule: allow
    proto: tcp
    port: "{{ node_exporter_port }}"
    from_ip: "{{ local_ipv4_subnet }}"

- name: Allow node-exporter over local IPv6
  ufw:
    rule: allow
    proto: tcp
    port: "{{ node_exporter_port }}"
    from_ip: "{{ local_ipv6_subnet }}"
