- name: Install UFW
  become: true
  apt:
    name: ufw
    state: present
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Allow SSH over local IPv4
  become: true
  ufw:
    rule: allow
    name: ssh
    from_ip: 192.168.0.0/16

- name: Allow SSH over local IPv6
  become: true
  ufw:
    rule: allow
    name: ssh
    from_ip: 2602:b8:6585:1e00::/64
