- name: Install UFW
  become: true
  apt:
    name: ufw
    state: present
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Allow incoming connections from specified sources
  become: true
  ufw:
    rule: allow
    from_ip: "{{ item }}"
  loop: "{{ ufw_allowed_ips }}"
