- name: Allow DNS over local IPv4
  ufw:
    rule: allow
    port: "{{ dnscrypt_proxy_port }}"
    from_ip: 192.168.0.0/16

- name: Allow DNS over local IPv6
  ufw:
    rule: allow
    port: "{{ dnscrypt_proxy_port }}"
    from_ip: 2602:b8:6585:1e00::/64
