- name: Install nginx-{{ nginx_flavor }}
  package:
    name: nginx-{{ nginx_flavor }}
    state: present

- name: Disable default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Enable and start nginx service
  service:
    name: nginx
    enabled: true
    state: started

- import_tasks: ufw.yml
