- name: Install nginx-{{ nginx_flavor }}
  apt:
    name: nginx-{{ nginx_flavor }}
    state: present
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Disable default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Enable and start nginx service
  service:
    name: nginx
    enabled: true
    state: started

- import_tasks: ufw.yml
