- name: Allow HTTP over local IPv4
  ufw:
    rule: allow
    name: www
    from_ip: 192.168.0.0/16

- name: Allow HTTPS over local IPv4
  ufw:
    rule: allow
    name: www secure
    from_ip: 192.168.0.0/16

- name: Allow HTTP over local IPv6
  ufw:
    rule: allow
    name: www
    from_ip: 2602:b8:6585:1e00::/64

- name: Allow HTTPS over local IPv6
  ufw:
    rule: allow
    name: www secure
    from_ip: 2602:b8:6585:1e00::/64
